services:
  postgres:
    image: postgres:15-alpine
    container_name: table-order-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: table_order
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: table-order-redis
    ports:
      - "6379:6379"

volumes:
  pg_data: